### PR TITLE
Drop support for Python 2.7 and 3.4

### PR DESCRIPTION
**Pull request by and-semakin**
This PR may be controversial, but my reasoning is that the modern `pytest` versions don't support for these interpreter's versions anyway.

See: https://github.com/pytest-dev/pytest/blob/master/setup.cfg

### CODE REVIEW

**Comment by nipunn1313** [comment]
interesting - will consider! I know at dbx we use py2.7 in a couple of places - but that may be ok (can ask to use a lower version of pytest-flakefinder in those places)

Can you add some information in the Changelog about dropping this support?

I think it would be helpful to also add some information to the README (a section about how to run with 2.7 - use pytest-flakefinder 0.1.3) - as I suspect there will continue to be some legacy use cases of 2.7 for a little longer.

Generally in favor of moving toward the future like this.

**Comment by and-semakin** [comment]
Hi @nipunn1313! Sure, I'll update the changelog.

Note that I've also added `python_requires` line into `setup.py`. This metadata parameter should solve the issue for users of older Python versions. If on Python 2.7 one will try to run `pip install pytest-flakefinder`, `pip` will automatically install the latest available version of the package for the current interpreter version (0.1.3).

See more info about it: https://packaging.python.org/guides/dropping-older-python-versions/

For Python 3.5+ we should bump the version of the package. What do you think, will it be 0.2.0 or 1.0.0?

**Comment by nipunn1313** [comment]
lets go to 1.0.0 - it's been stable enough!

**Comment by and-semakin** [comment]
I think that we are good to go. Please, let me know if there is something I need to fix.

**Comment by nipunn1313** [comment]
lgtm!

**Pull request merged**
